// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceaowalwdlsycinpauaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlYW93YWx3ZGxzeWNpbnBhdWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTg3MzAsImV4cCI6MjA2NzE3NDczMH0.VtFauZnSlUSrPF1x5F_G3zncGNs_UAl4-KmSGO0jO_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});